; Generated by slimec (stage 2)
; Target: windows-x64

section .data
str0: db "============================================", 0
str0_len equ $ - str0 - 1
str1: db 10, 0
str1_len equ $ - str1 - 1
str2: db "    Sreyt Calculator Application", 0
str2_len equ $ - str2 - 1
str3: db 0
str3_len equ 0
str4: db "Calculator: Initialized", 0
str4_len equ $ - str4 - 1
str5: db "--- Demo: Calculate 12 + 34 ---", 0
str5_len equ $ - str5 - 1
str6: db "--- Demo: Calculate 100 - 37 ---", 0
str6_len equ $ - str6 - 1
str7: db "--- Demo: Calculate 6 * 7 ---", 0
str7_len equ $ - str7 - 1
str8: db "--- Demo: Calculate 144 / 12 ---", 0
str8_len equ $ - str8 - 1
str9: db "--- Demo: Division by zero ---", 0
str9_len equ $ - str9 - 1
str10: db "    Calculator Demo Complete", 0
str10_len equ $ - str10 - 1
str11: db "Calculator: DIV, stored =", 0
str11_len equ $ - str11 - 1
str12: db " ", 0
str12_len equ $ - str12 - 1
str13: db "Calculator: Input digit", 0
str13_len equ $ - str13 - 1
str14: db "->", 0
str14_len equ $ - str14 - 1
str15: db "Calculator: Negated ->", 0
str15_len equ $ - str15 - 1
str16: db "Calculator: Result =", 0
str16_len equ $ - str16 - 1
str17: db "Calculator: Display =", 0
str17_len equ $ - str17 - 1
str18: db "Calculator: MUL, stored =", 0
str18_len equ $ - str18 - 1
str19: db "Calculator: ADD, stored =", 0
str19_len equ $ - str19 - 1
str20: db "Calculator: Cleared all", 0
str20_len equ $ - str20 - 1
str21: db "Calculator Error:", 0
str21_len equ $ - str21 - 1
str22: db "Calculator: Cleared entry", 0
str22_len equ $ - str22 - 1
str23: db "Calculator:", 0
str23_len equ $ - str23 - 1
str24: db "+", 0
str24_len equ $ - str24 - 1
str25: db "=", 0
str25_len equ $ - str25 - 1
str26: db "-", 0
str26_len equ $ - str26 - 1
str27: db "*", 0
str27_len equ $ - str27 - 1
str28: db "Division by zero", 0
str28_len equ $ - str28 - 1
str29: db "/", 0
str29_len equ $ - str29 - 1
str30: db "Calculator: SUB, stored =", 0
str30_len equ $ - str30 - 1

section .bss
_global_calc_window: resq 1
_global_display_entry: resq 1
_global_current_value: resq 1
_global_stored_value: resq 1
_global_current_operator: resq 1
_global_is_new_input: resq 1
_global_has_error: resq 1
_global_OP_NONE: resq 1
_global_OP_ADD: resq 1
_global_OP_SUB: resq 1
_global_OP_MUL: resq 1
_global_OP_DIV: resq 1
_itoa_buf: resb 24

section .text
global Start
extern GetStdHandle
extern WriteFile
extern ExitProcess

Start:
    push rbp
    mov rbp, rsp
    sub rsp, 2048
    and rsp, -16
    mov rax, 0
    mov [_global_calc_window], rax
    mov rax, 0
    mov [_global_display_entry], rax
    mov rax, 0
    mov [_global_current_value], rax
    mov rax, 0
    mov [_global_stored_value], rax
    mov rax, 0
    mov [_global_current_operator], rax
    mov rax, 1
    mov [_global_is_new_input], rax
    mov rax, 0
    mov [_global_has_error], rax
    mov rax, 0
    mov [_global_OP_NONE], rax
    mov rax, 1
    mov [_global_OP_ADD], rax
    mov rax, 2
    mov [_global_OP_SUB], rax
    mov rax, 3
    mov [_global_OP_MUL], rax
    mov rax, 4
    mov [_global_OP_DIV], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str0]
    mov r8, str0_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str2]
    mov r8, str2_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str0]
    mov r8, str0_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str3]
    mov r8, str3_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, 0
    mov [_global_current_value], rax
    mov rax, 0
    mov [_global_stored_value], rax
    mov rax, 0
    mov [_global_current_operator], rax
    mov rax, 1
    mov [_global_is_new_input], rax
    mov rax, 0
    mov [_global_has_error], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str4]
    mov r8, str4_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str3]
    mov r8, str3_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str5]
    mov r8, str5_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    call digit_1_click
    call digit_2_click
    call add_click
    call digit_3_click
    call digit_4_click
    call equals_click
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str3]
    mov r8, str3_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str6]
    mov r8, str6_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    call clear_click
    call digit_1_click
    call digit_0_click
    call digit_0_click
    call sub_click
    call digit_3_click
    call digit_7_click
    call equals_click
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str3]
    mov r8, str3_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str7]
    mov r8, str7_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    call clear_click
    call digit_6_click
    call mul_click
    call digit_7_click
    call equals_click
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str3]
    mov r8, str3_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str8]
    mov r8, str8_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    call clear_click
    call digit_1_click
    call digit_4_click
    call digit_4_click
    call div_click
    call digit_1_click
    call digit_2_click
    call equals_click
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str3]
    mov r8, str3_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str9]
    mov r8, str9_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    call clear_click
    call digit_4_click
    call digit_2_click
    call div_click
    call digit_0_click
    call equals_click
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str3]
    mov r8, str3_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str0]
    mov r8, str0_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str10]
    mov r8, str10_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str0]
    mov r8, str0_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, 0
    call ExitProcess

; Helper: int to string (rax = number, returns rdi = buffer, rax = length)
_itoa:
    push rbx
    push rcx
    push rdx
    mov rcx, _itoa_buf + 20
    mov rbx, 10
    xor r8, r8
    cmp rax, 0
    jge .positive
    neg rax
    mov r8, 1
.positive:
.loop:
    xor rdx, rdx
    div rbx
    add dl, '0'
    dec rcx
    mov [rcx], dl
    test rax, rax
    jnz .loop
    cmp r8, 1
    jne .done
    dec rcx
    mov byte [rcx], '-'
.done:
    mov rdi, rcx
    mov rax, _itoa_buf + 20
    sub rax, rcx
    pop rdx
    pop rcx
    pop rbx
    ret

div_click:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    call perform_pending_operation
    mov rax, [_global_OP_DIV]
    mov [_global_current_operator], rax
    mov rax, [_global_current_value]
    mov [_global_stored_value], rax
    mov rax, 1
    mov [_global_is_new_input], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str11]
    mov r8, str11_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_stored_value]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    xor rax, rax
    leave
    ret

digit_8_click:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov rax, 8
    mov rdi, rax
    call input_digit
    xor rax, rax
    leave
    ret

input_digit:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov [rbp-8], rdi
    mov rax, 1
    push rax
    mov rax, [_global_is_new_input]
    pop rbx
    cmp rax, rbx
    sete al
    movzx rax, al
    test rax, rax
    jz .L1
    mov rax, [rbp-8]
    mov [_global_current_value], rax
    mov rax, 0
    mov [_global_is_new_input], rax
    jmp .L0
.L1:
    mov rax, [rbp-8]
    push rax
    mov rax, 10
    push rax
    mov rax, [_global_current_value]
    pop rbx
    imul rax, rbx
    pop rbx
    add rax, rbx
    mov [_global_current_value], rax
.L0:
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str13]
    mov r8, str13_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [rbp-8]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str14]
    mov r8, str14_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_current_value]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    xor rax, rax
    leave
    ret

negate_click:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov rax, [_global_current_value]
    push rax
    mov rax, 0
    pop rbx
    sub rax, rbx
    mov [_global_current_value], rax
    mov rax, [_global_current_value]
    mov rdi, rax
    call update_display
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str15]
    mov r8, str15_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_current_value]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    xor rax, rax
    leave
    ret

equals_click:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    call perform_pending_operation
    mov rax, [_global_OP_NONE]
    mov [_global_current_operator], rax
    mov rax, 1
    mov [_global_is_new_input], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str16]
    mov r8, str16_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_current_value]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    xor rax, rax
    leave
    ret

digit_7_click:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov rax, 7
    mov rdi, rax
    call input_digit
    xor rax, rax
    leave
    ret

digit_2_click:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov rax, 2
    mov rdi, rax
    call input_digit
    xor rax, rax
    leave
    ret

digit_9_click:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov rax, 9
    mov rdi, rax
    call input_digit
    xor rax, rax
    leave
    ret

update_display:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov [rbp-8], rdi
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str17]
    mov r8, str17_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [rbp-8]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    xor rax, rax
    leave
    ret

clear_error:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov rax, 0
    mov [_global_has_error], rax
    xor rax, rax
    leave
    ret

digit_3_click:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov rax, 3
    mov rdi, rax
    call input_digit
    xor rax, rax
    leave
    ret

mul_click:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    call perform_pending_operation
    mov rax, [_global_OP_MUL]
    mov [_global_current_operator], rax
    mov rax, [_global_current_value]
    mov [_global_stored_value], rax
    mov rax, 1
    mov [_global_is_new_input], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str18]
    mov r8, str18_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_stored_value]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    xor rax, rax
    leave
    ret

digit_1_click:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov rax, 1
    mov rdi, rax
    call input_digit
    xor rax, rax
    leave
    ret

add_click:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    call perform_pending_operation
    mov rax, [_global_OP_ADD]
    mov [_global_current_operator], rax
    mov rax, [_global_current_value]
    mov [_global_stored_value], rax
    mov rax, 1
    mov [_global_is_new_input], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str19]
    mov r8, str19_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_stored_value]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    xor rax, rax
    leave
    ret

clear_click:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov rax, 0
    mov [_global_current_value], rax
    mov rax, 0
    mov [_global_stored_value], rax
    mov rax, [_global_OP_NONE]
    mov [_global_current_operator], rax
    mov rax, 1
    mov [_global_is_new_input], rax
    call clear_error
    mov rax, 0
    mov rdi, rax
    call update_display
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str20]
    mov r8, str20_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    xor rax, rax
    leave
    ret

digit_0_click:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov rax, 0
    mov rdi, rax
    call input_digit
    xor rax, rax
    leave
    ret

show_error:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov [rbp-8], rdi
    mov rax, 1
    mov [_global_has_error], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str21]
    mov r8, str21_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [rbp-8]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    xor rax, rax
    leave
    ret

clear_entry_click:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov rax, 0
    mov [_global_current_value], rax
    mov rax, 1
    mov [_global_is_new_input], rax
    call clear_error
    mov rax, 0
    mov rdi, rax
    call update_display
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str22]
    mov r8, str22_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    xor rax, rax
    leave
    ret

digit_5_click:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov rax, 5
    mov rdi, rax
    call input_digit
    xor rax, rax
    leave
    ret

perform_pending_operation:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov rax, [_global_OP_NONE]
    push rax
    mov rax, [_global_current_operator]
    pop rbx
    cmp rax, rbx
    sete al
    movzx rax, al
    test rax, rax
    jz .L3
    xor rax, rax
    leave
    ret
    jmp .L2
.L3:
.L2:
    mov rax, 1
    push rax
    mov rax, [_global_has_error]
    pop rbx
    cmp rax, rbx
    sete al
    movzx rax, al
    test rax, rax
    jz .L5
    xor rax, rax
    leave
    ret
    jmp .L4
.L5:
.L4:
    mov rax, 0
    mov [rbp-8], rax
    mov rax, [_global_OP_ADD]
    push rax
    mov rax, [_global_current_operator]
    pop rbx
    cmp rax, rbx
    sete al
    movzx rax, al
    test rax, rax
    jz .L7
    mov rax, [_global_current_value]
    push rax
    mov rax, [_global_stored_value]
    pop rbx
    add rax, rbx
    mov [rbp-8], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str23]
    mov r8, str23_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_stored_value]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str24]
    mov r8, str24_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_current_value]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str25]
    mov r8, str25_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [rbp-8]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    jmp .L6
.L7:
.L6:
    mov rax, [_global_OP_SUB]
    push rax
    mov rax, [_global_current_operator]
    pop rbx
    cmp rax, rbx
    sete al
    movzx rax, al
    test rax, rax
    jz .L9
    mov rax, [_global_current_value]
    push rax
    mov rax, [_global_stored_value]
    pop rbx
    sub rax, rbx
    mov [rbp-8], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str23]
    mov r8, str23_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_stored_value]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str26]
    mov r8, str26_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_current_value]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str25]
    mov r8, str25_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [rbp-8]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    jmp .L8
.L9:
.L8:
    mov rax, [_global_OP_MUL]
    push rax
    mov rax, [_global_current_operator]
    pop rbx
    cmp rax, rbx
    sete al
    movzx rax, al
    test rax, rax
    jz .L11
    mov rax, [_global_current_value]
    push rax
    mov rax, [_global_stored_value]
    pop rbx
    imul rax, rbx
    mov [rbp-8], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str23]
    mov r8, str23_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_stored_value]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str27]
    mov r8, str27_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_current_value]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str25]
    mov r8, str25_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [rbp-8]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    jmp .L10
.L11:
.L10:
    mov rax, [_global_OP_DIV]
    push rax
    mov rax, [_global_current_operator]
    pop rbx
    cmp rax, rbx
    sete al
    movzx rax, al
    test rax, rax
    jz .L13
    mov rax, 0
    push rax
    mov rax, [_global_current_value]
    pop rbx
    cmp rax, rbx
    sete al
    movzx rax, al
    test rax, rax
    jz .L15
    lea rax, [str28]
    mov rdi, rax
    call show_error
    xor rax, rax
    leave
    ret
    jmp .L14
.L15:
.L14:
    mov rax, [_global_current_value]
    push rax
    mov rax, [_global_stored_value]
    pop rbx
    cqo
    idiv rbx
    mov [rbp-8], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str23]
    mov r8, str23_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_stored_value]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str29]
    mov r8, str29_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_current_value]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str25]
    mov r8, str25_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [rbp-8]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    jmp .L12
.L13:
.L12:
    mov rax, [rbp-8]
    mov [_global_current_value], rax
    mov rax, [rbp-8]
    mov rdi, rax
    call update_display
    xor rax, rax
    leave
    ret

sub_click:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    call perform_pending_operation
    mov rax, [_global_OP_SUB]
    mov [_global_current_operator], rax
    mov rax, [_global_current_value]
    mov [_global_stored_value], rax
    mov rax, 1
    mov [_global_is_new_input], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str30]
    mov r8, str30_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_stored_value]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    xor rax, rax
    leave
    ret

digit_4_click:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov rax, 4
    mov rdi, rax
    call input_digit
    xor rax, rax
    leave
    ret

digit_6_click:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov rax, 6
    mov rdi, rax
    call input_digit
    xor rax, rax
    leave
    ret
