; Generated by slimec (stage 2)
; Target: windows-x64
; Mode: GUI (Win32)

section .data
; Win32 Constants
_gui_class_name: db "SlimeGUIClass", 0
_gui_btn_class: db "BUTTON", 0
_gui_edit_class: db "EDIT", 0
_gui_static_class: db "STATIC", 0
str0: db "Hello Slime GUI!", 0
str0_len equ $ - str0 - 1
str1: db "Welcome to Slime Lang!", 0
str1_len equ $ - str1 - 1
str2: db "This is a real Win32 GUI window.", 0
str2_len equ $ - str2 - 1
str3: db "Click Me!", 0
str3_len equ $ - str3 - 1

section .bss
; GUI Runtime Variables
_gui_hInstance: resq 1
_gui_main_hwnd: resq 1
_gui_wndclass: resb 80
_gui_msg: resb 48
_gui_ctrl_handles: resq 64
_gui_callbacks: resq 64
_gui_text_buffer: resb 256
_gui_next_id: resd 1
_itoa_buf: resb 24

section .text
; Win32 GUI Application
global Start

extern GetModuleHandleA
extern RegisterClassExA
extern CreateWindowExA
extern ShowWindow
extern UpdateWindow
extern GetMessageA
extern TranslateMessage
extern DispatchMessageA
extern PostQuitMessage
extern DefWindowProcA
extern ExitProcess
extern GetStdHandle
extern WriteFile
extern SetWindowTextA
extern GetWindowTextA
extern GetWindowTextLengthA
extern SendMessageA
extern LoadCursorA
extern MessageBoxA


Start:
    push rbp
    mov rbp, rsp
    sub rsp, 2048
    and rsp, -16

    ; Initialize GUI
    call _gui_init

    ; User code starts here
    lea rax, [str0]
    mov rdi, rax
    mov rax, 400
    mov rsi, rax
    mov rax, 300
    mov rdx, rax
    call window_create
    mov rax, 0
    mov rdi, rax
    lea rax, [str1]
    mov rsi, rax
    mov rax, 50
    mov rdx, rax
    mov rax, 50
    mov rcx, rax
    mov rax, 300
    mov r8, rax
    mov rax, 30
    mov r9, rax
    call label_create
    mov rax, 0
    mov rdi, rax
    lea rax, [str2]
    mov rsi, rax
    mov rax, 50
    mov rdx, rax
    mov rax, 90
    mov rcx, rax
    mov rax, 300
    mov r8, rax
    mov rax, 30
    mov r9, rax
    call label_create
    mov rax, 0
    mov rdi, rax
    lea rax, [str3]
    mov rsi, rax
    mov rax, 150
    mov rdx, rax
    mov rax, 150
    mov rcx, rax
    mov rax, 100
    mov r8, rax
    mov rax, 40
    mov r9, rax
    call button_create
    mov rax, 0
    mov rdi, rax
    mov rax, 50
    mov rsi, rax
    mov rax, 200
    mov rdx, rax
    mov rax, 300
    mov rcx, rax
    mov rax, 25
    mov r8, rax
    call entry_create

    ; Enter message loop
    call _gui_message_loop

    ; Exit
    xor rcx, rcx
    call ExitProcess

; Helper: int to string (rax = number, returns rdi = buffer, rax = length)
_itoa:
    push rbx
    push rcx
    push rdx
    mov rcx, _itoa_buf + 20
    mov rbx, 10
    xor r8, r8
    cmp rax, 0
    jge .positive
    neg rax
    mov r8, 1
.positive:
.loop:
    xor rdx, rdx
    div rbx
    add dl, '0'
    dec rcx
    mov [rcx], dl
    test rax, rax
    jnz .loop
    cmp r8, 1
    jne .done
    dec rcx
    mov byte [rcx], '-'
.done:
    mov rdi, rcx
    mov rax, _itoa_buf + 20
    sub rax, rcx
    pop rdx
    pop rcx
    pop rbx
    ret

; ======== GUI Runtime Functions ========

_gui_init:
    push rbp
    mov rbp, rsp
    sub rsp, 96
    
    ; GetModuleHandleA(NULL)
    xor rcx, rcx
    call GetModuleHandleA
    mov [_gui_hInstance], rax
    
    ; Initialize control ID counter
    mov dword [_gui_next_id], 1000
    
    ; Register window class
    lea rdi, [_gui_wndclass]
    mov dword [rdi], 80          ; cbSize
    mov dword [rdi+4], 0         ; style
    lea rax, [_gui_wndproc]
    mov [rdi+8], rax             ; lpfnWndProc
    mov dword [rdi+16], 0        ; cbClsExtra
    mov dword [rdi+20], 0        ; cbWndExtra
    mov rax, [_gui_hInstance]
    mov [rdi+24], rax            ; hInstance
    mov qword [rdi+32], 0        ; hIcon
    ; Load cursor
    xor rcx, rcx
    mov rdx, 32512               ; IDC_ARROW
    call LoadCursorA
    lea rdi, [_gui_wndclass]
    mov [rdi+40], rax            ; hCursor
    mov qword [rdi+48], 16       ; hbrBackground = COLOR_BTNFACE+1
    mov qword [rdi+56], 0        ; lpszMenuName
    lea rax, [_gui_class_name]
    mov [rdi+64], rax            ; lpszClassName
    mov qword [rdi+72], 0        ; hIconSm
    
    lea rcx, [_gui_wndclass]
    call RegisterClassExA
    
    leave
    ret

_gui_wndproc:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rbp-8], rcx             ; hwnd
    mov [rbp-16], rdx            ; msg
    mov [rbp-24], r8             ; wParam
    mov [rbp-32], r9             ; lParam
    
    ; Check message type
    cmp edx, 0x0002              ; WM_DESTROY
    je .on_destroy
    cmp edx, 0x0111              ; WM_COMMAND
    je .on_command
    jmp .default
    
.on_destroy:
    xor rcx, rcx
    call PostQuitMessage
    xor rax, rax
    jmp .done
    
.on_command:
    ; LOWORD(wParam) = control ID
    mov rax, [rbp-24]
    movzx ecx, ax                ; control ID
    sub ecx, 1000
    cmp ecx, 64
    jae .default
    ; Get callback address
    lea rax, [_gui_callbacks]
    mov rax, [rax + rcx*8]
    test rax, rax
    jz .default
    ; Call callback
    call rax
    xor rax, rax
    jmp .done
    
.default:
    mov rcx, [rbp-8]
    mov rdx, [rbp-16]
    mov r8, [rbp-24]
    mov r9, [rbp-32]
    call DefWindowProcA
    
.done:
    leave
    ret

_gui_message_loop:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    
.loop:
    lea rcx, [_gui_msg]
    xor rdx, rdx
    xor r8, r8
    xor r9, r9
    call GetMessageA
    test eax, eax
    jle .done
    
    lea rcx, [_gui_msg]
    call TranslateMessage
    
    lea rcx, [_gui_msg]
    call DispatchMessageA
    
    jmp .loop
    
.done:
    leave
    ret

; window_create(title, width, height)
window_create:
    push rbp
    mov rbp, rsp
    sub rsp, 128
    mov [rbp-8], rdi             ; title
    mov [rbp-16], rsi            ; width
    mov [rbp-24], rdx            ; height
    
    ; CreateWindowExA
    xor rcx, rcx                 ; dwExStyle
    lea rdx, [_gui_class_name]   ; lpClassName
    mov r8, [rbp-8]              ; lpWindowName
    mov r9d, 0x10CF0000          ; WS_OVERLAPPEDWINDOW | WS_VISIBLE
    mov dword [rsp+32], 100      ; x
    mov dword [rsp+40], 100      ; y
    mov rax, [rbp-16]
    mov [rsp+48], eax            ; width
    mov rax, [rbp-24]
    mov [rsp+56], eax            ; height
    mov qword [rsp+64], 0        ; hWndParent
    mov qword [rsp+72], 0        ; hMenu
    mov rax, [_gui_hInstance]
    mov [rsp+80], rax            ; hInstance
    mov qword [rsp+88], 0        ; lpParam
    call CreateWindowExA
    mov [_gui_main_hwnd], rax
    
    leave
    ret

; button_create(parent, text, x, y, w, h)
button_create:
    push rbp
    mov rbp, rsp
    sub rsp, 128
    mov [rbp-8], rdi             ; parent (ignored, use main)
    mov [rbp-16], rsi            ; text
    mov [rbp-24], rdx            ; x
    mov [rbp-32], rcx            ; y
    mov [rbp-40], r8             ; width
    mov [rbp-48], r9             ; height
    
    ; Get control ID
    mov eax, [_gui_next_id]
    mov [rbp-56], eax
    inc dword [_gui_next_id]
    
    xor rcx, rcx                 ; dwExStyle
    lea rdx, [_gui_btn_class]    ; BUTTON
    mov r8, [rbp-16]             ; text
    mov r9d, 0x50010000          ; WS_CHILD|WS_VISIBLE|WS_TABSTOP
    mov eax, [rbp-24]
    mov [rsp+32], eax            ; x
    mov eax, [rbp-32]
    mov [rsp+40], eax            ; y
    mov rax, [rbp-40]
    mov [rsp+48], eax            ; width
    mov rax, [rbp-48]
    mov [rsp+56], eax            ; height
    mov rax, [_gui_main_hwnd]
    mov [rsp+64], rax            ; hWndParent
    mov eax, [rbp-56]
    mov [rsp+72], rax            ; hMenu = control ID
    mov rax, [_gui_hInstance]
    mov [rsp+80], rax            ; hInstance
    mov qword [rsp+88], 0        ; lpParam
    call CreateWindowExA
    
    ; Store handle
    mov ecx, [rbp-56]
    sub ecx, 1000
    lea rdx, [_gui_ctrl_handles]
    mov [rdx + rcx*8], rax
    
    mov eax, [rbp-56]            ; return control ID
    leave
    ret

; label_create(parent, text, x, y, w, h)
label_create:
    push rbp
    mov rbp, rsp
    sub rsp, 128
    mov [rbp-16], rsi            ; text
    mov [rbp-24], rdx            ; x
    mov [rbp-32], rcx            ; y
    mov [rbp-40], r8             ; width
    mov [rbp-48], r9             ; height
    
    mov eax, [_gui_next_id]
    mov [rbp-56], eax
    inc dword [_gui_next_id]
    
    xor rcx, rcx
    lea rdx, [_gui_static_class] ; STATIC
    mov r8, [rbp-16]
    mov r9d, 0x50000000          ; WS_CHILD|WS_VISIBLE
    mov eax, [rbp-24]
    mov [rsp+32], eax
    mov eax, [rbp-32]
    mov [rsp+40], eax
    mov rax, [rbp-40]
    mov [rsp+48], eax
    mov rax, [rbp-48]
    mov [rsp+56], eax
    mov rax, [_gui_main_hwnd]
    mov [rsp+64], rax
    mov eax, [rbp-56]
    mov [rsp+72], rax
    mov rax, [_gui_hInstance]
    mov [rsp+80], rax
    mov qword [rsp+88], 0
    call CreateWindowExA
    
    mov ecx, [rbp-56]
    sub ecx, 1000
    lea rdx, [_gui_ctrl_handles]
    mov [rdx + rcx*8], rax
    
    mov eax, [rbp-56]
    leave
    ret

; entry_create(parent, x, y, w, h)
entry_create:
    push rbp
    mov rbp, rsp
    sub rsp, 128
    mov [rbp-24], rsi            ; x
    mov [rbp-32], rdx            ; y
    mov [rbp-40], rcx            ; width
    mov [rbp-48], r8             ; height
    
    mov eax, [_gui_next_id]
    mov [rbp-56], eax
    inc dword [_gui_next_id]
    
    mov rcx, 0x200               ; WS_EX_CLIENTEDGE
    lea rdx, [_gui_edit_class]   ; EDIT
    xor r8, r8                   ; empty text
    mov r9d, 0x50810080          ; WS_CHILD|WS_VISIBLE|WS_BORDER|WS_TABSTOP|ES_AUTOHSCROLL
    mov eax, [rbp-24]
    mov [rsp+32], eax
    mov eax, [rbp-32]
    mov [rsp+40], eax
    mov rax, [rbp-40]
    mov [rsp+48], eax
    mov rax, [rbp-48]
    mov [rsp+56], eax
    mov rax, [_gui_main_hwnd]
    mov [rsp+64], rax
    mov eax, [rbp-56]
    mov [rsp+72], rax
    mov rax, [_gui_hInstance]
    mov [rsp+80], rax
    mov qword [rsp+88], 0
    call CreateWindowExA
    
    mov ecx, [rbp-56]
    sub ecx, 1000
    lea rdx, [_gui_ctrl_handles]
    mov [rdx + rcx*8], rax
    
    mov eax, [rbp-56]
    leave
    ret

; gui_set_text(ctrl_id, text)
gui_set_text:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    
    ; Get handle from ID
    mov eax, edi
    sub eax, 1000
    lea rcx, [_gui_ctrl_handles]
    mov rcx, [rcx + rax*8]
    mov rdx, rsi                 ; text
    call SetWindowTextA
    
    leave
    ret

; gui_get_text(ctrl_id) -> ptr to text
gui_get_text:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    
    ; Get handle from ID
    mov eax, edi
    sub eax, 1000
    lea rcx, [_gui_ctrl_handles]
    mov rcx, [rcx + rax*8]
    mov rdx, 255
    lea r8, [_gui_text_buffer]
    call GetWindowTextA
    
    lea rax, [_gui_text_buffer]
    leave
    ret

; gui_on_click(ctrl_id, callback_ptr)
gui_on_click:
    push rbp
    mov rbp, rsp
    
    mov eax, edi
    sub eax, 1000
    lea rcx, [_gui_callbacks]
    mov [rcx + rax*8], rsi
    
    leave
    ret

; msgbox(text, title)
msgbox:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    
    mov r8, rsi                  ; title
    mov rdx, rdi                 ; text
    xor rcx, rcx                 ; hWnd = NULL
    xor r9, r9                   ; MB_OK
    call MessageBoxA
    
    leave
    ret
