; Generated by slimec (stage 2)
; Target: windows-x64

section .data
str0: db "===== Slime æ¨¡åç³»ç»æµè¯ =====", 0
str0_len equ $ - str0 - 1
str1: db 10, 0
str1_len equ $ - str1 - 1
str2: db 0
str2_len equ 0
str3: db "--- æ°å­¦è¿ç® ---", 0
str3_len equ $ - str3 - 1
str4: db "a =", 0
str4_len equ $ - str4 - 1
str5: db " ", 0
str5_len equ $ - str5 - 1
str6: db "b =", 0
str6_len equ $ - str6 - 1
str7: db "add(a, b) =", 0
str7_len equ $ - str7 - 1
str8: db "sub(a, b) =", 0
str8_len equ $ - str8 - 1
str9: db "mul(a, b) =", 0
str9_len equ $ - str9 - 1
str10: db "div(a, b) =", 0
str10_len equ $ - str10 - 1
str11: db "--- é«çº§è¿ç® ---", 0
str11_len equ $ - str11 - 1
str12: db "factorial(5) =", 0
str12_len equ $ - str12 - 1
str13: db "power(2, 3) =", 0
str13_len equ $ - str13 - 1
str14: db "abs(-42) =", 0
str14_len equ $ - str14 - 1
str15: db "max(7, 12) =", 0
str15_len equ $ - str15 - 1
str16: db "min(7, 12) =", 0
str16_len equ $ - str16 - 1
str17: db "===== æµè¯å®æ =====", 0
str17_len equ $ - str17 - 1

section .bss
_global_PI_INT: resq 1
_global_E_INT: resq 1
_global_a: resq 1
_global_b: resq 1
_global_sum: resq 1
_global_diff: resq 1
_global_prod: resq 1
_global_quot: resq 1
_global_fact5: resq 1
_global_pow23: resq 1
_global_abs_neg: resq 1
_global_max_val: resq 1
_global_min_val: resq 1
_itoa_buf: resb 24

section .text
global Start
extern GetStdHandle
extern WriteFile
extern ExitProcess

Start:
    push rbp
    mov rbp, rsp
    sub rsp, 2048
    and rsp, -16
    mov rax, 3
    mov [_global_PI_INT], rax
    mov rax, 2
    mov [_global_E_INT], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str0]
    mov r8, str0_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str2]
    mov r8, str2_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str3]
    mov r8, str3_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, 10
    mov [_global_a], rax
    mov rax, 3
    mov [_global_b], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str4]
    mov r8, str4_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str5]
    mov r8, str5_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, 10
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str6]
    mov r8, str6_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str5]
    mov r8, str5_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, 3
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str2]
    mov r8, str2_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, 10
    mov rdi, rax
    mov rax, 3
    mov rsi, rax
    call add
    mov [_global_sum], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str7]
    mov r8, str7_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str5]
    mov r8, str5_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_sum]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, 10
    mov rdi, rax
    mov rax, 3
    mov rsi, rax
    call sub
    mov [_global_diff], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str8]
    mov r8, str8_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str5]
    mov r8, str5_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_diff]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, 10
    mov rdi, rax
    mov rax, 3
    mov rsi, rax
    call mul
    mov [_global_prod], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str9]
    mov r8, str9_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str5]
    mov r8, str5_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_prod]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, 10
    mov rdi, rax
    mov rax, 3
    mov rsi, rax
    call div
    mov [_global_quot], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str10]
    mov r8, str10_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str5]
    mov r8, str5_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_quot]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str2]
    mov r8, str2_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str11]
    mov r8, str11_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, 5
    mov rdi, rax
    call factorial
    mov [_global_fact5], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str12]
    mov r8, str12_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str5]
    mov r8, str5_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_fact5]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, 2
    mov rdi, rax
    mov rax, 3
    mov rsi, rax
    call power
    mov [_global_pow23], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str13]
    mov r8, str13_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str5]
    mov r8, str5_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_pow23]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, -42
    mov rdi, rax
    call abs
    mov [_global_abs_neg], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str14]
    mov r8, str14_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str5]
    mov r8, str5_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_abs_neg]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, 7
    mov rdi, rax
    mov rax, 12
    mov rsi, rax
    call max
    mov [_global_max_val], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str15]
    mov r8, str15_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str5]
    mov r8, str5_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_max_val]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, 7
    mov rdi, rax
    mov rax, 12
    mov rsi, rax
    call min
    mov [_global_min_val], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str16]
    mov r8, str16_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str5]
    mov r8, str5_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, [_global_min_val]
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str2]
    mov r8, str2_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str17]
    mov r8, str17_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, 0
    call ExitProcess

; Helper: int to string (rax = number, returns rdi = buffer, rax = length)
_itoa:
    push rbx
    push rcx
    push rdx
    mov rcx, _itoa_buf + 20
    mov rbx, 10
    xor r8, r8
    cmp rax, 0
    jge .positive
    neg rax
    mov r8, 1
.positive:
.loop:
    xor rdx, rdx
    div rbx
    add dl, '0'
    dec rcx
    mov [rcx], dl
    test rax, rax
    jnz .loop
    cmp r8, 1
    jne .done
    dec rcx
    mov byte [rcx], '-'
.done:
    mov rdi, rcx
    mov rax, _itoa_buf + 20
    sub rax, rcx
    pop rdx
    pop rcx
    pop rbx
    ret

div:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov [rbp-8], rdi
    mov [rbp-16], rsi
    mov rax, 0
    push rax
    mov rax, [rbp-16]
    pop rbx
    cmp rax, rbx
    sete al
    movzx rax, al
    test rax, rax
    jz .L1
    mov rax, 0
    leave
    ret
    jmp .L0
.L1:
.L0:
    mov rax, [rbp-16]
    push rax
    mov rax, [rbp-8]
    pop rbx
    cqo
    idiv rbx
    leave
    ret
    xor rax, rax
    leave
    ret

add:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov [rbp-8], rdi
    mov [rbp-16], rsi
    mov rax, [rbp-16]
    push rax
    mov rax, [rbp-8]
    pop rbx
    add rax, rbx
    leave
    ret
    xor rax, rax
    leave
    ret

power:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov [rbp-8], rdi
    mov [rbp-16], rsi
    mov rax, 0
    push rax
    mov rax, [rbp-16]
    pop rbx
    cmp rax, rbx
    sete al
    movzx rax, al
    test rax, rax
    jz .L3
    mov rax, 1
    leave
    ret
    jmp .L2
.L3:
.L2:
    mov rax, 1
    mov [rbp-24], rax
    mov rax, 0
    mov [rbp-32], rax
.L4:
    mov rax, [rbp-16]
    push rax
    mov rax, [rbp-32]
    pop rbx
    cmp rax, rbx
    setl al
    movzx rax, al
    test rax, rax
    jz .L5
    mov rax, [rbp-8]
    push rax
    mov rax, [rbp-24]
    pop rbx
    imul rax, rbx
    mov [rbp-24], rax
    mov rbx, [rbp-32]
    mov rax, 1
    add rbx, rax
    mov [rbp-32], rbx
    jmp .L4
.L5:
    mov rax, [rbp-24]
    leave
    ret
    xor rax, rax
    leave
    ret

min:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov [rbp-8], rdi
    mov [rbp-16], rsi
    mov rax, [rbp-16]
    push rax
    mov rax, [rbp-8]
    pop rbx
    cmp rax, rbx
    setl al
    movzx rax, al
    test rax, rax
    jz .L7
    mov rax, [rbp-8]
    leave
    ret
    jmp .L6
.L7:
.L6:
    mov rax, [rbp-16]
    leave
    ret
    xor rax, rax
    leave
    ret

max:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov [rbp-8], rdi
    mov [rbp-16], rsi
    mov rax, [rbp-16]
    push rax
    mov rax, [rbp-8]
    pop rbx
    cmp rax, rbx
    setg al
    movzx rax, al
    test rax, rax
    jz .L9
    mov rax, [rbp-8]
    leave
    ret
    jmp .L8
.L9:
.L8:
    mov rax, [rbp-16]
    leave
    ret
    xor rax, rax
    leave
    ret

mul:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov [rbp-8], rdi
    mov [rbp-16], rsi
    mov rax, [rbp-16]
    push rax
    mov rax, [rbp-8]
    pop rbx
    imul rax, rbx
    leave
    ret
    xor rax, rax
    leave
    ret

abs:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov [rbp-8], rdi
    mov rax, 0
    push rax
    mov rax, [rbp-8]
    pop rbx
    cmp rax, rbx
    setl al
    movzx rax, al
    test rax, rax
    jz .L11
    mov rax, [rbp-8]
    push rax
    mov rax, 0
    pop rbx
    sub rax, rbx
    leave
    ret
    jmp .L10
.L11:
.L10:
    mov rax, [rbp-8]
    leave
    ret
    xor rax, rax
    leave
    ret

sub:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov [rbp-8], rdi
    mov [rbp-16], rsi
    mov rax, [rbp-16]
    push rax
    mov rax, [rbp-8]
    pop rbx
    sub rax, rbx
    leave
    ret
    xor rax, rax
    leave
    ret

factorial:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    mov [rbp-8], rdi
    mov rax, 1
    push rax
    mov rax, [rbp-8]
    pop rbx
    cmp rax, rbx
    setle al
    movzx rax, al
    test rax, rax
    jz .L13
    mov rax, 1
    leave
    ret
    jmp .L12
.L13:
.L12:
    mov rax, 1
    push rax
    mov rax, [rbp-8]
    pop rbx
    sub rax, rbx
    mov rdi, rax
    call factorial
    push rax
    mov rax, [rbp-8]
    pop rbx
    imul rax, rbx
    leave
    ret
    xor rax, rax
    leave
    ret
