; Generated by slimec (stage 2)
; Target: windows-x64

section .data
str0: db "===== Include æµè¯ =====", 0
str0_len equ $ - str0 - 1
str1: db 10, 0
str1_len equ $ - str1 - 1
str2: db "MAX_SIZE =", 0
str2_len equ $ - str2 - 1
str3: db " ", 0
str3_len equ $ - str3 - 1
str4: db "MIN_SIZE =", 0
str4_len equ $ - str4 - 1
str5: db "DEFAULT_VALUE =", 0
str5_len equ $ - str5 - 1
str6: db "è¿æ¯éè¿ debug_print æ¥å£è¾åºç", 0
str6_len equ $ - str6 - 1
str7: db "===== æµè¯å®æ =====", 0
str7_len equ $ - str7 - 1

section .bss
_global_MAX_SIZE: resq 1
_global_MIN_SIZE: resq 1
_global_DEFAULT_VALUE: resq 1
_itoa_buf: resb 24

section .text
global Start
extern GetStdHandle
extern WriteFile
extern ExitProcess

Start:
    push rbp
    mov rbp, rsp
    sub rsp, 2048
    and rsp, -16
    mov rax, 100
    mov [_global_MAX_SIZE], rax
    mov rax, 1
    mov [_global_MIN_SIZE], rax
    mov rax, 0
    mov [_global_DEFAULT_VALUE], rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str0]
    mov r8, str0_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str2]
    mov r8, str2_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str3]
    mov r8, str3_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, 100
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str4]
    mov r8, str4_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str3]
    mov r8, str3_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, 1
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str5]
    mov r8, str5_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str3]
    mov r8, str3_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, 0
    call _itoa
    push rdi
    push rax
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    pop r8
    pop rdx
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str6]
    mov r8, str6_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str7]
    mov r8, str7_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [str1]
    mov r8, str1_len
    lea r9, [rbp-200]
    mov qword [rsp+32], 0
    call WriteFile
    mov rcx, 0
    call ExitProcess

; Helper: int to string (rax = number, returns rdi = buffer, rax = length)
_itoa:
    push rbx
    push rcx
    push rdx
    mov rcx, _itoa_buf + 20
    mov rbx, 10
    xor r8, r8
    cmp rax, 0
    jge .positive
    neg rax
    mov r8, 1
.positive:
.loop:
    xor rdx, rdx
    div rbx
    add dl, '0'
    dec rcx
    mov [rcx], dl
    test rax, rax
    jnz .loop
    cmp r8, 1
    jne .done
    dec rcx
    mov byte [rcx], '-'
.done:
    mov rdi, rcx
    mov rax, _itoa_buf + 20
    sub rax, rcx
    pop rdx
    pop rcx
    pop rbx
    ret
