; Generated by slimec (stage 2)
; Target: windows-x64

section .data
str0: db "Hello, Slime!", 0
str0_len equ $ - str0 - 1

section .bss
_itoa_buf: resb 24

section .text
global Start
extern GetStdHandle
extern WriteFile
extern ExitProcess

Start:
    push rbp
    mov rbp, rsp
    sub rsp, 2048
    and rsp, -16
    lea rax, [str0]
    mov rdi, rax
    call io_println
    mov rcx, 0
    call ExitProcess

; Helper: int to string (rax = number, returns rdi = buffer, rax = length)
_itoa:
    push rbx
    push rcx
    push rdx
    mov rcx, _itoa_buf + 20
    mov rbx, 10
    xor r8, r8
    cmp rax, 0
    jge .positive
    neg rax
    mov r8, 1
.positive:
.loop:
    xor rdx, rdx
    div rbx
    add dl, '0'
    dec rcx
    mov [rcx], dl
    test rax, rax
    jnz .loop
    cmp r8, 1
    jne .done
    dec rcx
    mov byte [rcx], '-'
.done:
    mov rdi, rcx
    mov rax, _itoa_buf + 20
    sub rax, rcx
    pop rdx
    pop rcx
    pop rbx
    ret
